import type { Metadata } from "next";
import NavBar from "@/components/navbar";
import RootContext from "@/components/root-context";

import '@fontsource-variable/inter';
import '@fontsource/noto-sans-thai-looped/400.css';
import '@fontsource/noto-sans-thai-looped/700.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootContext>
          <NavBar />
          <div className="border-2 border-red-400">{children}</div>
        </RootContext>
      </body>
    </html>
  );
}
